const labels = {
    LOW_TO_HIGH: "LOW_TO_HIGH",
    HIGH_TO_LOW: "HIGH_TO_LOW",
    EXCLUDE_OUT_OF_STOCK: "EXCLUDE_OUT_OF_STOCK",
    RESET_FILTERS: "RESET_FILTERS",
    ADD_TO_CART: "ADD_TO_CART",
    ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
    INCREMENT_QUANTITY: "INCREMNT_QUANTITY",
    DECREMENT_QUANTITY: "DECREMENT_QUANTITY",
    REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
    REMOVE_ITEM: "REMOVE_ITEM"
}

export { labels };